// AUTO-GENERATED by scripts/sync-airtable.mjs — do not edit by hand.
// Re-run with: npm run sync
// Source: Airtable base appxxnxrfm14M9ZmV

import type { Activity } from "../mock";

export const activity: Activity[] = [
  {
    "id": "a1",
    "type": "experience",
    "title": "Horseback with Drei Parker",
    "subtitle": "Sat, May 17 · 4:00 PM",
    "date": "Upcoming",
    "status": "upcoming",
    "amount": 1998,
    "photo": "https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?auto=format&fit=crop&w=200&q=80"
  },
  {
    "id": "a2",
    "type": "rental",
    "title": "Mitsubishi Montero Sport",
    "subtitle": "SHOTCORNER CORP. · 3 days",
    "date": "May 4 – May 7",
    "status": "completed",
    "amount": 13500,
    "photo": "/cars/mitsubishi-montero.webp"
  },
  {
    "id": "a3",
    "type": "rental",
    "title": "Toyota HiAce GL Grandia",
    "subtitle": "SHOTCORNER CORP. · 1 day",
    "date": "Apr 18",
    "status": "canceled",
    "amount": 0,
    "photo": "/cars/toyota-hiace.jpg"
  },
  {
    "id": "a5",
    "type": "ride",
    "title": "Ride to Shot Corner",
    "subtitle": "Andrei Mercado · Toyota HiAce",
    "date": "May 9 · 2:34 PM",
    "status": "canceled",
    "amount": 0,
    "photo": "https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=200&q=80"
  },
  {
    "id": "a6",
    "type": "ride",
    "title": "Ride to NAIA T3",
    "subtitle": "Marco Reyes · Mirage",
    "date": "May 7 · 6:15 AM",
    "status": "completed",
    "amount": 420,
    "photo": "https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=200&q=80"
  }
];
