// AUTO-GENERATED by scripts/sync-airtable.mjs — do not edit by hand.
// Re-run with: npm run sync
// Source: Airtable base appxxnxrfm14M9ZmV

import type { Car } from "../mock";

export const cars: Car[] = [
  {
    "id": "c1",
    "make": "Toyota",
    "model": "HiAce GL Grandia",
    "year": 2023,
    "category": "van",
    "pricePerDay": 5500,
    "rating": 4.93,
    "trips": 92,
    "location": "Cabanatuan City",
    "hostName": "SHOTCORNER CORP.",
    "hostPhoto": "https://i.pravatar.cc/150?img=33",
    "hostSuperhost": true,
    "photo": "/cars/toyota-hiace.jpg",
    "features": [
      "12-seater",
      "Diesel auto",
      "USB ports"
    ],
    "instantBook": true,
    "driverOption": "both"
  },
  {
    "id": "c2",
    "make": "Nissan",
    "model": "NV350 Urvan Premium",
    "year": 2022,
    "category": "van",
    "pricePerDay": 5200,
    "rating": 4.88,
    "trips": 71,
    "location": "Cabanatuan City",
    "hostName": "SHOTCORNER CORP.",
    "hostPhoto": "https://i.pravatar.cc/150?img=33",
    "hostSuperhost": true,
    "photo": "/cars/nissan-nv350.jpg",
    "features": [
      "15-seater",
      "Reclining seats",
      "Captain's chairs"
    ],
    "instantBook": true,
    "driverOption": "both"
  },
  {
    "id": "c3",
    "make": "Nissan",
    "model": "Almera",
    "year": 2024,
    "category": "sedan",
    "pricePerDay": 2800,
    "rating": 4.91,
    "trips": 58,
    "location": "Cabanatuan City",
    "hostName": "SHOTCORNER CORP.",
    "hostPhoto": "https://i.pravatar.cc/150?img=33",
    "hostSuperhost": true,
    "photo": "/cars/nissan-almera.avif",
    "features": [
      "Compact sedan",
      "Fuel-efficient",
      "Push start"
    ],
    "instantBook": true,
    "driverOption": "both"
  },
  {
    "id": "c4",
    "make": "Honda",
    "model": "BR-V",
    "year": 2024,
    "category": "suv",
    "pricePerDay": 3200,
    "rating": 4.94,
    "trips": 124,
    "location": "Cabanatuan City",
    "hostName": "SHOTCORNER CORP.",
    "hostPhoto": "https://i.pravatar.cc/150?img=33",
    "hostSuperhost": true,
    "photo": "/cars/honda-brv.avif",
    "features": [
      "7-seater",
      "Fuel-efficient",
      "Family-friendly"
    ],
    "instantBook": true,
    "driverOption": "both"
  },
  {
    "id": "c5",
    "make": "Mitsubishi",
    "model": "Montero Sport",
    "year": 2023,
    "category": "suv",
    "pricePerDay": 4500,
    "rating": 4.96,
    "trips": 87,
    "location": "Cabanatuan City",
    "hostName": "SHOTCORNER CORP.",
    "hostPhoto": "https://i.pravatar.cc/150?img=33",
    "hostSuperhost": true,
    "photo": "/cars/mitsubishi-montero.webp",
    "features": [
      "7-seater 4x4",
      "Diesel turbo",
      "Paddle shifters"
    ],
    "instantBook": false,
    "driverOption": "both"
  },
  {
    "id": "c7",
    "make": "Vespa",
    "model": "Primavera Justin Bieber Ed.",
    "year": 2024,
    "category": "motorcycle",
    "pricePerDay": 1200,
    "rating": 5,
    "trips": 24,
    "location": "Cabanatuan City",
    "hostName": "SHOTCORNER CORP.",
    "hostPhoto": "https://i.pravatar.cc/150?img=33",
    "hostSuperhost": true,
    "photo": "/cars/vespa-jb.jpg",
    "features": [
      "Limited edition",
      "150cc",
      "2 helmets incl."
    ],
    "instantBook": true,
    "driverOption": "self-drive",
    "regionTag": "Siargao"
  }
];
