// AUTO-GENERATED by scripts/sync-airtable.mjs — do not edit by hand.
// Re-run with: npm run sync
// Source: Airtable base appxxnxrfm14M9ZmV

import type { Review } from "../mock";

export const reviews: Review[] = [
  {
    "id": "r1",
    "carId": "c1",
    "reviewerName": "Patricia L.",
    "reviewerPhoto": "https://i.pravatar.cc/150?img=20",
    "rating": 5,
    "date": "April 2026",
    "text": "Shotcorner team was super organized — van was spotless on pickup and the AC was strong even with 10 of us. Used it for a Tagaytay trip, no issues at all."
  },
  {
    "id": "r2",
    "carId": "c1",
    "reviewerName": "Miguel T.",
    "reviewerPhoto": "https://i.pravatar.cc/150?img=11",
    "rating": 5,
    "date": "March 2026",
    "text": "Booked the HiAce for an out-of-town funeral. Driver was professional and got us there safely. Salamat po Shotcorner."
  },
  {
    "id": "r3",
    "carId": "c1",
    "reviewerName": "Reese M.",
    "reviewerPhoto": "https://i.pravatar.cc/150?img=45",
    "rating": 4,
    "date": "March 2026",
    "text": "Comfortable ride, USB ports were a nice touch. Slight delay on pickup but they communicated well."
  },
  {
    "id": "r4",
    "carId": "c1",
    "reviewerName": "Joel C.",
    "reviewerPhoto": "https://i.pravatar.cc/150?img=53",
    "rating": 5,
    "date": "February 2026",
    "text": "Used multiple times for company outings. Reliable every time."
  },
  {
    "id": "r5",
    "carId": "c2",
    "reviewerName": "Anna G.",
    "reviewerPhoto": "https://i.pravatar.cc/150?img=32",
    "rating": 5,
    "date": "April 2026",
    "text": "Captain's chairs make this so much more comfortable than a regular Urvan. 15 of us fit no problem."
  },
  {
    "id": "r6",
    "carId": "c2",
    "reviewerName": "Karlo D.",
    "reviewerPhoto": "https://i.pravatar.cc/150?img=17",
    "rating": 5,
    "date": "March 2026",
    "text": "Big group, long drive, zero complaints from anyone. Will book again."
  },
  {
    "id": "r7",
    "carId": "c2",
    "reviewerName": "Mika S.",
    "reviewerPhoto": "https://i.pravatar.cc/150?img=29",
    "rating": 4,
    "date": "January 2026",
    "text": "Solid van. Interior was clean and recliners actually recline. Took one star for fuel — diesel is on you, fyi."
  },
  {
    "id": "r8",
    "carId": "c3",
    "reviewerName": "Beatrice R.",
    "reviewerPhoto": "https://i.pravatar.cc/150?img=41",
    "rating": 5,
    "date": "April 2026",
    "text": "Perfect city car. Easy to park, sips fuel, and the Shotcorner team was super accommodating on pickup time."
  },
  {
    "id": "r9",
    "carId": "c3",
    "reviewerName": "Marvin O.",
    "reviewerPhoto": "https://i.pravatar.cc/150?img=52",
    "rating": 5,
    "date": "March 2026",
    "text": "Daily driver for a week — felt brand new. No drama."
  },
  {
    "id": "r10",
    "carId": "c3",
    "reviewerName": "Ysa P.",
    "reviewerPhoto": "https://i.pravatar.cc/150?img=38",
    "rating": 5,
    "date": "February 2026",
    "text": "First time using Sakay and Almera was a great intro. Push start is a nice touch for the price."
  },
  {
    "id": "r11",
    "carId": "c4",
    "reviewerName": "Don N.",
    "reviewerPhoto": "https://i.pravatar.cc/150?img=60",
    "rating": 5,
    "date": "April 2026",
    "text": "7-seater that actually fits adults in row 3. Took it to Subic, ~22 km/L on the trip. Shotcorner is a great host."
  },
  {
    "id": "r12",
    "carId": "c4",
    "reviewerName": "Sheila K.",
    "reviewerPhoto": "https://i.pravatar.cc/150?img=49",
    "rating": 5,
    "date": "March 2026",
    "text": "Family of 6, perfect size. Honda Sensing made the long drive way less stressful."
  },
  {
    "id": "r13",
    "carId": "c4",
    "reviewerName": "Ryan A.",
    "reviewerPhoto": "https://i.pravatar.cc/150?img=14",
    "rating": 5,
    "date": "February 2026",
    "text": "Pickup in Cabanatuan was a breeze. Shotcorner even threw in a baby seat I asked for last minute."
  },
  {
    "id": "r14",
    "carId": "c5",
    "reviewerName": "Chris F.",
    "reviewerPhoto": "https://i.pravatar.cc/150?img=58",
    "rating": 5,
    "date": "April 2026",
    "text": "Diesel torque is unreal. Took it to Baguio without breaking a sweat. Shotcorner knows their fleet well."
  },
  {
    "id": "r15",
    "carId": "c5",
    "reviewerName": "Trisha L.",
    "reviewerPhoto": "https://i.pravatar.cc/150?img=22",
    "rating": 5,
    "date": "March 2026",
    "text": "Spacious, powerful, immaculate interior. Paddle shifters were a fun bonus on mountain roads."
  },
  {
    "id": "r16",
    "carId": "c5",
    "reviewerName": "Bryan H.",
    "reviewerPhoto": "https://i.pravatar.cc/150?img=68",
    "rating": 5,
    "date": "January 2026",
    "text": "Used for a province wedding. Held our luggage + 6 adults comfortably. Shotcorner is responsive AF."
  },
  {
    "id": "r17",
    "carId": "c7",
    "reviewerName": "Sam V.",
    "reviewerPhoto": "https://i.pravatar.cc/150?img=42",
    "rating": 5,
    "date": "April 2026",
    "text": "Insanely fun to ride around General Luna on this. Felt like a vacation movie. Shotcorner's Siargao crew is a legend."
  },
  {
    "id": "r18",
    "carId": "c7",
    "reviewerName": "Hannah W.",
    "reviewerPhoto": "https://i.pravatar.cc/150?img=46",
    "rating": 5,
    "date": "March 2026",
    "text": "Vespa is in mint condition. Bieber stickers + Siargao = the most photogenic trip of my life."
  },
  {
    "id": "r19",
    "carId": "c7",
    "reviewerName": "Jake R.",
    "reviewerPhoto": "https://i.pravatar.cc/150?img=64",
    "rating": 5,
    "date": "March 2026",
    "text": "Smooth, easy to ride even if you've only been on automatics. Bring sunblock — open ride."
  }
];
